name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest
    permissions:
      # Needed for checkout
      contents: read
      # Needed for codecov OIDC token
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
      - run: npm run ci-test
      - uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v5
        with:
          use_oidc: true
      - uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v5
        with:
          use_oidc: true
          report_type: test_results
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Needed for the GitHub Actions OIDC token
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: goauthentik/action-setup-authentik@5b35e5951a1ec761847711a5d8170dbd67675526 # v3.3
        id: authentik
        with:
          version: stable
          sentry_env: goauthentik-configure-authentik-credentials-ci
          blueprints_path: .github/blueprints
      - uses: ./
        id: test-action
        with:
          authentik_url: ${{ steps.authentik.outputs.http_url }}
          client_id: ci
          scope: openid
      - name: Use token
        run: >-
          curl -fsS -H "Authorization: Bearer $TOKEN" "$AUTHENTIK_URL/application/o/userinfo/"
        env:
          TOKEN: ${{ steps.test-action.outputs.token }}
          AUTHENTIK_URL: ${{ steps.authentik.outputs.http_url }}
